id: IB984E1B3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T13:44:28+00:00'
last_modified: '2022-06-16T04:13:10.286254+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W27888
  title: བསྐྱེད་རིམ་སྤྱིའི་རྣམ་བཞག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    DC46:
      image_group_id: I4682
      title: ''
      total_pages: 194
      order: 1
      base_file: DC46.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
